changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
      - chore
    authors:
      - github-actions
      - dependabot

  categories:
    - title: "Changes"
      labels:
        - "*"
